// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZkbZpLw0R-m8_nej0pNR4evn1i2Ql0o',
    appId: '1:338097140484:web:36d33958c29b8fdeec9651',
    messagingSenderId: '338097140484',
    projectId: 'pawmatch-347f4',
    authDomain: 'pawmatch-347f4.firebaseapp.com',
    storageBucket: 'pawmatch-347f4.firebasestorage.app',
    measurementId: 'G-TFQ5N5J2JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvW2FbFQ8h3HwwIhtJAwzqz6Ea3Pl5C5I',
    appId: '1:338097140484:android:3481f81a2630509bec9651',
    messagingSenderId: '338097140484',
    projectId: 'pawmatch-347f4',
    storageBucket: 'pawmatch-347f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcSxRsGUEvPyg4pr9L1Jkkqofrili01gw',
    appId: '1:338097140484:ios:f838af2f8a310817ec9651',
    messagingSenderId: '338097140484',
    projectId: 'pawmatch-347f4',
    storageBucket: 'pawmatch-347f4.firebasestorage.app',
    iosClientId: '338097140484-h8hj6679a1ljru4t0k7heo2im8b45pv5.apps.googleusercontent.com',
    iosBundleId: 'com.danca.pawmatchMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcSxRsGUEvPyg4pr9L1Jkkqofrili01gw',
    appId: '1:338097140484:ios:f838af2f8a310817ec9651',
    messagingSenderId: '338097140484',
    projectId: 'pawmatch-347f4',
    storageBucket: 'pawmatch-347f4.firebasestorage.app',
    iosClientId: '338097140484-h8hj6679a1ljru4t0k7heo2im8b45pv5.apps.googleusercontent.com',
    iosBundleId: 'com.danca.pawmatchMobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZkbZpLw0R-m8_nej0pNR4evn1i2Ql0o',
    appId: '1:338097140484:web:0073eb23d5f5b00dec9651',
    messagingSenderId: '338097140484',
    projectId: 'pawmatch-347f4',
    authDomain: 'pawmatch-347f4.firebaseapp.com',
    storageBucket: 'pawmatch-347f4.firebasestorage.app',
    measurementId: 'G-184WXT5ZCH',
  );
}
